/* WRITE A JAVA PROGRAM THAT HAS CLASS SHAPE WHICH INCLUDES THAT ABSTRACT CLASS METHOD NAME getarea(), 
    class rectangle ,triangle and circle  INHERIT
     THE CLASS  SHAPRE AND IMPLEMENTS METHOD getarea AND RETURN VALUE OF AREA RESPECTIVELY */